# Generated by Django 4.2.17 on 2025-01-08 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetBusinesse',
            new_name='PetBusiness',
        ),
    ]
