# Generated by Django 4.2.17 on 2024-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_businesses',
            name='contact_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pet_businesses',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
