# Generated by Django 4.2.17 on 2025-01-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0002_rename_petbusinesse_petbusiness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='pet_businesse',
            new_name='pet_business',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('pet_business', 'author'), name='unique_like'),
        ),
    ]
