# Generated by Django 4.2.17 on 2025-01-15 09:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0003_remove_like_unique_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbusiness',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
