# Generated by Django 4.2.17 on 2024-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0004_alter_pet_businesses_unique_together_service_types_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet_Businesses',
            new_name='Pet_Businesse',
        ),
        migrations.RenameModel(
            old_name='Pet_Types',
            new_name='Pet_Type',
        ),
        migrations.RenameModel(
            old_name='Service_Types',
            new_name='Service_Type',
        ),
    ]
