# Generated by Django 4.2.17 on 2024-12-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0005_rename_pet_businesses_pet_businesse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_type',
            name='pet_business',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='pet_business',
        ),
        migrations.AddField(
            model_name='pet_businesse',
            name='business_pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_pet_types', to='pet_businesses.pet_type'),
        ),
        migrations.AddField(
            model_name='pet_businesse',
            name='business_service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_service_types', to='pet_businesses.service_type'),
        ),
    ]
