# Generated by Django 4.2.17 on 2024-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0006_remove_pet_type_pet_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_businesse',
            name='business_pet_type',
        ),
        migrations.RemoveField(
            model_name='pet_businesse',
            name='business_service_type',
        ),
        migrations.AddField(
            model_name='pet_businesse',
            name='business_pet_type',
            field=models.ManyToManyField(related_name='business_pet_types', to='pet_businesses.pet_type'),
        ),
        migrations.AddField(
            model_name='pet_businesse',
            name='business_service_type',
            field=models.ManyToManyField(related_name='business_service_types', to='pet_businesses.service_type'),
        ),
    ]
