# Generated by Django 4.2.17 on 2024-12-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_businesses', '0008_alter_pet_businesse_options_alter_pet_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_businesse',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='pet_businesse',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='pet_businesse',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='pet_businesse',
            name='contact_mobile',
        ),
        migrations.AddField(
            model_name='pet_businesse',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet_business_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
