# Generated by Django 4.2.17 on 2024-12-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0009_remove_pet_businesse_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_businesse',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
