# Generated by Django 4.2.17 on 2025-01-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_businesses', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
                ('pet_businesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pet_businesses.pet_businesse')),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('pet_businesse', 'author')},
            },
        ),
    ]
