# Generated by Django 4.2.17 on 2025-01-08 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_businesses', '0012_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet_Businesse',
            new_name='PetBusinesse',
        ),
        migrations.RenameModel(
            old_name='Service_Type',
            new_name='PetType',
        ),
        migrations.RenameModel(
            old_name='Pet_Type',
            new_name='ServiceType',
        ),
        migrations.AlterModelOptions(
            name='pettype',
            options={'ordering': ['pet_type']},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['service_type']},
        ),
        migrations.RenameField(
            model_name='pettype',
            old_name='service_type',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='pet_type',
            new_name='service_type',
        ),
    ]
