# Generated by Django 4.2.17 on 2025-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0014_alter_petbusinesse_options_alter_pettype_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('pet_businesse', 'author'), name='unique_like'),
        ),
    ]
